### ISSUE TITLE
queued-move.js gas price is static

### ISSUE THREAD

**Issue by solsticesolutions** [darkforest-eth/plugins#100]
queued-move.js needs to be updated to match the chosen gas price in settings instead of just using the default 1 gwei hard coded in the file.

This could fix issues with other plugins that rely on that resource for sends.

**Comment by phated** [comment]
It just needs to be removed from plugins. It was created at a time when the game would crash when creating too many moves with `df.move`

**Comment by phated** [comment]
It looks like it has been removed in every plugin, but we need to keep the file around for old plugins. So I'm closing this.
