### ISSUE TITLE
Plugin windows act weird when area is offscreen

### ISSUE THREAD

**Issue by modukon** [darkforest-eth/plugins#104]
Example:
Take a plugin window (any plugin) and minimize it.
Now move it to the bottom of the screen and maximize it again.
Its area should now be off-screen.
If you now click the window anywhere (even close button) it will not react to the click but instead position itself upwards so its area is again on the screen.

Suggestions:
- Only reposition plugin on click when its title bar is off-screen
(this way people can move it onscreen themselves and can have it off-screen on purpose if they don't want to see the whole plugin)
- If a plugin gets maximized automatically move its area on-screen (if possible), but also remember how it was when minimized so when you minimize it again it will move back to the minimized position.

If a plugin window grows too big, parts of it will spawn off-screen. (for example Player List - if you have many players on your map)
Is there a way to position your plugin somehow with code?
Or to make it so it will move on-screen again automatically?

**Comment by phated** [comment]
Yeah, this is a known bug, but it's also a game-client issue and not something that plugins can fix.

I'm going to cc @ner0nzz so it can be tracked by the DF team.
