### ISSUE TITLE
df.getTimeForMove() does not consider worm hole connection

### ISSUE THREAD

**Issue by modukon** [darkforest-eth/plugins#114]
https://github.com/darkforest-eth/client/blob/master/docs/classes/backend_gamelogic_gamemanager.default.md#gettimeformove

It will ignore the worm hole connection and return the wrong time.
I did not test it with photon cannons, might also return the wrong time.

**Comment by phated** [comment]
This has been migrated to the private issue tracker. Thanks for reporting @modukon!
