### ISSUE TITLE
Player List plugin - feature ideas

### ISSUE THREAD

**Issue by modukon** [darkforest-eth/plugins#129]
> This looks good but were going to need to continue to figure out how to not confuse people with the fact that its a list of players YOU CAN SEE. not a global list. For instance on my screen df_dao is #1 score with a total of 5 planets

I agree that this is a problem, i am not sure how to fix it.
Maybe display a message the first time the plugin is started that tells them this information and how the plugin works?
~~Maybe localStorage could be used to detect if the plugin was first started? It could store the version number of the plugin and when it sees the number does not exist or is lower it will override it and show the information message that explains the plugin.
Is this a good way or bad way of doing it? I never used localStorage~~

> Future requests:
> Id also like to a descending order sort on second click maybe, and maybe see an indicator for ascending descending sort and which column is currently being sorted by.

I agree this would be good.
What i also thought about:
- Showing energy growth and silver growth in the list
- Showing artifacts like so: 20/13/7/4/1
This player has 20 common, 13 rare, 7 epic, 4 legendary, 1 mythic artifact
The numbers could be in the colors of the artifact rarity.
The score of the artifacts can be calculated like this:
```
Common - 5k points
Rare - 20k points
Epic - 200k points
Legendary - 3M points
Mythic - 20M points
```
This allows to sort by artifact score.
- When clicking on the artifacts of a player a list could pop up that shows the artifacts, the stat boosts, and a button that allows to ui.centerPlanet the planet the artifact is located on.
- When clicking on the planet count of a player it teleports you to their biggest planet (right now it will do that if you click on a players row)
- When hovering over a players row the whole row becomes white / changes color for a visual indication
- When there is an option to click something the mouse turns into an hand and a small text appears that explains what will happen when you click, for example "list artifacts" or "teleport to player"
- Showing voyages in the list for each player: arriving voyages, attacking voyages, incoming attacks
Could be displayed similar to the artifacts: 5/0/2
And clicking on them could lead to a list of all voyages and more information about them
- Maybe make a boolean variable for each column in the player list that easily allows you to disable or enable them, so you can make the list smaller and dont show information you dont want to see.

**Comment by phated** [comment]
@modukon just want to make note that localstorage access is not allowed in community showcase plugins (with 1 exception currently). The players private key is stored in localstorage and we don't want plugins getting close to that.

**Comment by modukon** [comment]
> @modukon just want to make note that localstorage access is not allowed in community showcase plugins (with 1 exception currently). The players private key is stored in localstorage and we don't want plugins getting close to that.
Ok this makes a lot of sense, i saw another pr request for a plugin that was using it. Maybe there is a different way to explain to people how the plugin works

**Comment by modukon** [comment]
Closing this since most of it was done with the last pr.
But the plugin is not done jet. a lot of new things can still be added and improved in the future.
