### ISSUE TITLE
Centralize Resources is not working

### ISSUE THREAD

**Issue by St4rgarden** [darkforest-eth/plugins#81]
I am using a ton of the plugins successfully.

Hopefully I am not just being a n00b here but it appears the centralize resources plugin is not working

Just getting a message like this :
![image](https://user-images.githubusercontent.com/38195744/120911623-a2b4e180-c63d-11eb-989e-ba9c6f8e5dac.png)

**Comment by St4rgarden** [comment]
I don't do Javascript so - maybe I can get a friend to take a look at it.  Just hoping someone here wanted to fix it.

**Comment by Theminijohn** [comment]
@St4rgarden You selecting a planet to receive resources to, right?

**Comment by solsticesolutions** [comment]
queued-move.js needs to be updated to match the chosen gas price in settings instead of just using the default 1 gwei hard coded in the file.

This could also fix issues with other plugins that rely on that resource for sends.

**Comment by phated** [comment]
Can you try it now with the fix from #106 ?
